/*
This file was automatically generated by joi-to-typescript
Do not modify this file manually
*/

/**
 * The configuration format for the server
 */
export interface config {
	/**
	 * The database specific options
	 */
	database: databaseOptions;
	/**
	 * The game-specific options
	 */
	game: gameOptions;
	/**
	 * The web server options
	 */
	server: serverOptions;
}

/**
 * The database specific options
 */
export interface databaseOptions {
	/**
	 * The location indicator where the database is. This can be a filepath or a socket URI, depending on what database is being used.
	 */
	uri: string;
}

/**
 * The game-specific options
 */
export interface gameOptions {
	files: {
		/**
		 * Unknown Property
		 */
		[x: string]: unknown;
	};
	max_incorrect: number;
	/**
	 * The options for all of the penalties from actions
	 */
	penalties: penaltyOptions;
}

/**
 * The options for all of the penalties from actions
 */
export interface penaltyOptions {
	duplicate: number;
	guess: number;
	solve: number;
}

/**
 * The web server options
 */
export interface serverOptions {
	/**
	 * The port the server will run on
	 */
	port: number;
}
