/*
This file was automatically generated by joi-to-typescript
Do not modify this file manually
*/

/**
 * The custom headers Nightbot makes requests with
 */
export interface nightbotCustomHeaders {
	'nightbot-channel'?: string;
	'nightbot-response-url'?: string;
	'nightbot-user'?: string;
}
